name: npm-publish

on:
  push:
    tags:
      - '*' # Push events to every tag not containing "/" e.g. v1.0, v20.15.10

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Tests
        run: deno test --allow-env --allow-net --allow-read

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          matrix.os == 'ubuntu-latest' &&
          startsWith(github.repository, 'justjavac') &&
          startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true

      # Publish @netzo/sdk to npm on tag:
      # Note that the build script always runs even when not publishing.
      # This is to ensure your build and tests pass on each commit.
      # see https://github.com/denoland/dnt#github-actions---npm-publish-on-tag

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: npm build
        run: deno run -A ./scripts/build_npm.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}

      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd npm && npm publish
