name: test

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Test apis/jsonplaceholder
        run: deno test --allow-env --allow-net --allow-read --allow-run lib/apis/jsonplaceholder
